name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      env:
        GOPATH: /home/runner/go
      run: |
        sed -i -e "s,_ \"github.com/mattn/go-oci8\",,g" db.go
        sed -i -e "s,_ \"gopkg.in/rana/ora.v4\",,g" db.go
        sed -i -e "s,_ \"github.com/go-sql-driver/mysql\",,g" db.go
        sed -i -e "s,_ \"github.com/lib/pq\",,g" db.go
        make

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binaries
      id: upload-sqlshell
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./sqlshell
        asset_name: sqlshell
        asset_content_type: application/octet-stream
