name: Go

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build and test
      env:
        GOPATH: /home/runner/go
        PKG_CONFIG_PATH: /home/runner/go
      run: |
        curl -ksL https://gist.githubusercontent.com/vkuznet/6c1b1ded0a6b85da64a7c0a5386745ca/raw/3198086a7b6d8f41478e0423ff99cbe3616f547f/oci8.pc > /home/runner/go/oci8.pc
        sed -i -e "s,_ \"github.com/mattn/go-oci8\",,g" db.go
        sed -i -e "s,_ \"gopkg.in/rana/ora.v4\",,g" db.go
        mkdir -p $GOPATH/src/github.com/vkuznet
        cp -r ../sqlshell $GOPATH/src/github.com/vkuznet
#         make test-github
